In [26]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import seaborn as sns

In [27]:
data=pd.read_csv('C:/Users/sai kiran/Downloads/loan_final313 - Copy.csv')
data.head()

id  year     issue_d  final_d  emp_length_int home_ownership  \
0  1077501  2011  01/12/2011  1012015            10.0           RENT   
1  1077430  2011  01/12/2011  1042013             0.5           RENT   
2  1077175  2011  01/12/2011  1062014            10.0           RENT   
3  1076863  2011  01/12/2011  1012015            10.0           RENT   
4  1075358  2011  01/12/2011  1012016             1.0           RENT   

   home_ownership_cat income_category  annual_inc  income_cat    ...     \
0                   1             Low       24000           1    ...      
1                   1             Low       30000           1    ...      
2                   1             Low       12252           1    ...      
3                   1             Low       49200           1    ...      
4                   1             Low       80000           1    ...      

   loan_condition_cat interest_rate  grade grade_cat    dti   total_pymnt  \
0                   0         10.65      B         2  27.65   5861.071414   
1                   1         15.27      C         3   1.00   1008.710000   
2                   0         15.96      C         3   8.72   3003.653644   
3                   0         13.49      C         3  20.00  12226.302210   
4                   0         12.69      B         2  17.94   3242.170000   

   total_rec_prncp recoveries  installment    region  
0          5000.00       0.00       162.87   munster  
1           456.46     117.08        59.83  leinster  
2          2400.00       0.00        84.33  cannught  
3         10000.00       0.00       339.31    ulster  
4          2233.10       0.00        67.79    ulster  

[5 rows x 30 columns]

## Feature Elimination
### will remove all redundant features as both the columns such as 'home_ownership' and 'home_ownership_cat' mean the same
### will remove features such as ''application_type_cat'' as they doesn't impact the target class (from visualisation)

In [28]:
data.drop(['id','home_ownership','income_category','loan_condition_cat','total_pymnt','annual_inc','total_rec_prncp','term','application_type','purpose','interest_payments','grade','dti','application_type_cat','recoveries'],axis=1,inplace=True)
data.head()

year     issue_d  final_d  emp_length_int  home_ownership_cat  income_cat  \
0  2011  01/12/2011  1012015            10.0                   1           1   
1  2011  01/12/2011  1042013             0.5                   1           1   
2  2011  01/12/2011  1062014            10.0                   1           1   
3  2011  01/12/2011  1012015            10.0                   1           1   
4  2011  01/12/2011  1012016             1.0                   1           1   

   loan_amount  term_cat  purpose_cat  interest_payment_cat loan_condition  \
0         5000         1            1                     1      Good Loan   
1         2500         2            2                     2       Bad Loan   
2         2400         1            3                     2      Good Loan   
3        10000         1            4                     2      Good Loan   
4         3000         2            4                     1      Good Loan   

   interest_rate  grade_cat  installment    region  
0          10.65          2       162.87   munster  
1          15.27          3        59.83  leinster  
2          15.96          3        84.33  cannught  
3          13.49          3       339.31    ulster  
4          12.69          2        67.79    ulster

### Handling categorical values

In [29]:
data['region'].value_counts()

leinster        214646
ulster          208731
Northern-Irl    204399
cannught        155029
munster         104574
Name: region, dtype: int64

In [30]:
data['region'].replace('leinster',0,inplace=True)
data['region'].replace('ulster',1,inplace=True)
data['region'].replace('Northern-Irl',2,inplace=True)
data['region'].replace('cannught',3,inplace=True)
data['region'].replace('munster',4,inplace=True)

In [31]:
data['region'].value_counts()

0    214646
1    208731
2    204399
3    155029
4    104574
Name: region, dtype: int64

In [32]:
data['year'].value_counts()

2015    421094
2014    235628
2013    134755
2012     53367
2011     21721
2010     12537
2009      5281
2008      2393
2007       603
Name: year, dtype: int64

In [33]:
### Creating New Features  length=issue_d - final_d

In [34]:
data.drop(['issue_d','final_d'],axis=1,inplace=True)

### Applying Binning to Numerical features (from visualisation) 

In [35]:
bins=[0,2,8,11]
labels=[0,1,2]
data['emp_length_int']=pd.cut(data['emp_length_int'],bins=bins,labels=labels)

In [36]:
data['emp_length_int'].value_counts()

1    354583
2    326226
0    206570
Name: emp_length_int, dtype: int64

In [37]:
bins=[0,5000,20000,35000]
labels=[0,1,2]
data['loan_amount']=pd.cut(data['loan_amount'],bins=bins,labels=labels)

In [38]:
data['loan_amount'].value_counts()

1    583862
2    200837
0    102680
Name: loan_amount, dtype: int64

In [39]:
bins=[0,5,10,15,20,25,30]
labels=[0,1,2,3,4,5]
data['interest_rate']=pd.cut(data['interest_rate'],bins=bins,labels=labels)

In [40]:
data['interest_rate'].value_counts()

2    372060
1    235621
3    221068
4     52137
5      6493
0         0
Name: interest_rate, dtype: int64

In [41]:
bins=[0,300,600,800,1200,1400]
labels=[0,1,2,3,4]
data['installment']=pd.cut(data['installment'],bins=bins,labels=labels)

In [42]:
data['installment'].value_counts()

1    397791
0    288874
2    120875
3     73014
4      6790
Name: installment, dtype: int64

In [43]:
data.head()

year emp_length_int  home_ownership_cat  income_cat loan_amount  term_cat  \
0  2011              2                   1           1           0         1   
1  2011              0                   1           1           0         2   
2  2011              2                   1           1           0         1   
3  2011              2                   1           1           1         1   
4  2011              0                   1           1           0         2   

   purpose_cat  interest_payment_cat loan_condition interest_rate  grade_cat  \
0            1                     1      Good Loan             2          2   
1            2                     2       Bad Loan             3          3   
2            3                     2      Good Loan             3          3   
3            4                     2      Good Loan             2          3   
4            4                     1      Good Loan             2          2   

  installment  region  
0           0       4  
1           0       0  
2           0       3  
3           1       1  
4           0       1

### Label Encoder

In [44]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data['year']=l.fit_transform(data['year'])
l=LabelEncoder()
data['loan_condition']=l.fit_transform(data['loan_condition'])

### Algorithemic Part

In [45]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.linear_model import LogisticRegression,Perceptron
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
data=data.dropna()
data.to_csv (r'C:/Users/sai kiran/Desktop/export_dataframe.csv', index = False, header=True)
y=data['loan_condition'].values
data.drop('loan_condition',axis=1,inplace=True)
x=data[:].values
y=y.reshape(-1, 1)
print(x.shape,y.shape)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)

(887344, 12) (887344, 1)


In [46]:
print(x,y)
print(x.shape,y.shape)

[[4 2 1 ... 2 0 4]
 [4 0 1 ... 3 0 0]
 [4 2 1 ... 3 0 3]
 ...
 [8 1 1 ... 4 1 0]
 [8 0 1 ... 5 1 2]
 [8 2 1 ... 2 2 0]] [[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [1]]
(887344, 12) (887344, 1)


In [48]:
from sklearn.metrics import precision_recall_fscore_support
logistic=LogisticRegression()
forest=RandomForestClassifier
logistic.fit(x_train,y_train)
pred=logistic.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)
precision_recall_fscore_support(y_test, pred, average='macro')

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


0.9237727457138135


(0.6203183703014098, 0.5008937843438375, 0.48234365679201496, None)

### Decision Tree

In [49]:
from sklearn import tree
from sklearn.metrics import precision_recall_fscore_support
clf = tree.DecisionTreeClassifier()
clf.fit(x_train,y_train)
pred=clf.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)
precision_recall_fscore_support(y_test, pred, average='macro')

0.9046332887559917


(0.5537538964989098, 0.5224325371365321, 0.5261124509372492, None)

### Naive Bayes

In [50]:
from sklearn.naive_bayes import GaussianNB
clf= GaussianNB()
clf.fit(x_train,y_train)
pred=clf.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)
precision_recall_fscore_support(y_test, pred, average='macro')

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


0.8825487220327268


(0.5733360493410691, 0.5696943147586072, 0.5714338600499478, None)

### SVM

In [51]:
#from sklearn import svm
#clf = svm.SVC()
#clf.fit(x_train,y_train)
#pred=clf.predict(x_test)
#print(accuracy_score(pred,y_test))
#confusion_matrix(pred,y_test)
#precision_recall_fscore_support(y_test, pred, average='macro')

### Random Forest

In [52]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=8, random_state=0)
clf.fit(x_train,y_train)
pred=clf.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)
precision_recall_fscore_support(y_test, pred, average='macro')

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


0.9239643281092695


C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(0.46198216405463477, 0.5, 0.4802398436447487, None)

# ANN

In [54]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(16, input_dim=12, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train,y_train, epochs=80, batch_size=30)

Epoch 1/80
621140/621140 [==============================] - 21s 34us/step - loss: 0.2438 - acc: 0.9238
Epoch 2/80
621140/621140 [==============================] - 20s 33us/step - loss: 0.2412 - acc: 0.9240
Epoch 3/80
621140/621140 [==============================] - 21s 33us/step - loss: 0.2405 - acc: 0.9240
Epoch 4/80
621140/621140 [==============================] - 21s 33us/step - loss: 0.2401 - acc: 0.9240
Epoch 5/80
621140/621140 [==============================] - 21s 33us/step - loss: 0.2398 - acc: 0.9240
Epoch 6/80
621140/621140 [==============================] - 21s 33us/step - loss: 0.2396 - acc: 0.9240
Epoch 7/80
621140/621140 [==============================] - 21s 33us/step - loss: 0.2394 - acc: 0.9240
Epoch 8/80
621140/621140 [==============================] - 21s 33us/step - loss: 0.2393 - acc: 0.9240
Epoch 9/80
621140/621140 [==============================] - 21s 33us/step - loss: 0.2393 - acc: 0.9240
Epoch 10/80
621140/621140 [==============================] - 21s 34us/ste

621140/621140 [==============================] - 25s 40us/step - loss: 0.2384 - acc: 0.9240
Epoch 79/80
621140/621140 [==============================] - 25s 40us/step - loss: 0.2384 - acc: 0.9240
Epoch 80/80
621140/621140 [==============================] - 28s 45us/step - loss: 0.2384 - acc: 0.9240


In [55]:
_,accuracy = model.evaluate(x_test,y_test)

266204/266204 [==============================] - 5s 19us/step


In [56]:
pred=model.predict_classes(x_test)

In [57]:
precision_recall_fscore_support(y_test, pred, average='macro')

C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(0.46198216405463477, 0.5, 0.4802398436447487, None)

In [58]:
accuracy

0.9239643281110609