In [8]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import seaborn as sns

In [9]:
data=pd.read_csv('C:/Users/sai kiran/Desktop/export_dataframe.csv')
data.head()

year  emp_length_int  home_ownership_cat  income_cat  loan_amount  \
0     4               2                   1           1            0   
1     4               0                   1           1            0   
2     4               2                   1           1            0   
3     4               2                   1           1            1   
4     4               0                   1           1            0   

   term_cat  purpose_cat  interest_payment_cat  loan_condition  \
0         1            1                     1               1   
1         2            2                     2               0   
2         1            3                     2               1   
3         1            4                     2               1   
4         2            4                     1               1   

   loan_condition_cat  interest_rate  grade_cat  total_pymnt  total_rec_prncp  \
0                   0              2          2            1                1   
1                   1              3          3            0                0   
2                   0              3          3            0                0   
3                   0              2          3            2                2   
4                   0              2          2            0                0   

   installment  region  
0            0       4  
1            0       0  
2            0       3  
3            1       1  
4            0       1

In [10]:
len(data)

868946

### PCA

In [11]:
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression,Perceptron
pca = PCA(n_components=7)
y=data['loan_condition'].values
data.drop('loan_condition',axis=1,inplace=True)
X=data[:].values
y=y.reshape(-1, 1)
x = pca.fit_transform(X)
x_train,x_test,y_train,y_test = train_test_split(x,y)
print(x,y)
print(x.shape,y.shape)

[[-3.89033159  0.70221104 -0.55043146 ...  3.5980004   0.32616547
  -0.61837064]
 [-2.57360641 -0.47335884  1.10778408 ...  3.56383806  0.24722377
   1.30412549]
 [-1.63698658 -0.48756871  0.72132122 ...  3.75646572  0.63843281
  -0.3080254 ]
 ...
 [ 1.36886125 -1.80124989  1.69727841 ... -0.26325107 -0.84901322
  -0.05701211]
 [ 1.49000122 -1.78102935  2.43949179 ...  0.27783921 -1.20297361
   0.66202739]
 [-3.97976231  0.30564926  0.05612705 ... -1.18177052 -1.06652835
  -0.94058596]] [[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [1]]
(868946, 7) (868946, 1)


In [12]:
logistic=LogisticRegression()
logistic.fit(x_train,y_train)
pred=logistic.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9226328848216464


array([[   732,    835],
       [ 15972, 199698]], dtype=int64)

### SVD

In [13]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=7, n_iter=7, random_state=42)
x=svd.fit_transform(X)
x_train,x_test,y_train,y_test = train_test_split(x,y)
print(x,y)
print(x.shape,y.shape)

[[ 5.8629641  -1.94162721  0.95583903 ...  2.97758581  0.24603548
  -0.90830959]
 [ 6.02678213 -0.90744814 -0.48618375 ... -0.46600214  0.16229419
  -0.55144603]
 [ 7.10041812 -0.48471104 -0.5398549  ...  2.31497091  0.56906647
  -0.50040235]
 ...
 [11.30112296  0.20613271 -1.8027795  ... -1.4817908  -0.84176319
   0.19303247]
 [11.79741471 -0.04246692 -1.66524908 ...  0.55593499 -1.18718956
   0.41584132]
 [ 8.3401751  -3.51766241  1.10021739 ... -2.06793018 -1.06343728
  -0.08068079]] [[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [1]]
(868946, 7) (868946, 1)


In [14]:
logistic=LogisticRegression()
logistic.fit(x_train,y_train)
pred=logistic.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9239402127630192


array([[  1429,   1350],
       [ 15173, 199285]], dtype=int64)

### NMF

In [21]:
from sklearn.decomposition import NMF
clf = NMF(n_components=7)
x=clf.fit_transform(X)
x_train,x_test,y_train,y_test = train_test_split(x,y)
print(x,y)
print(x.shape,y.shape)

[[0.04603559 0.00638998 0.02430767 ... 0.06903978 0.02277713 0.        ]
 [0.04614425 0.01904524 0.00060001 ... 0.00039564 0.0121065  0.        ]
 [0.04602647 0.03165668 0.0007001  ... 0.0518335  0.02224891 0.        ]
 ...
 [0.09060019 0.06331889 0.         ... 0.         0.00985049 0.0200669 ]
 [0.08933949 0.06342811 0.         ... 0.03474352 0.00038105 0.02123405]
 [0.08890804 0.00056775 0.03523073 ... 0.         0.0169376  0.035077  ]] [[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [1]]
(868946, 7) (868946, 1)


In [22]:
logistic=LogisticRegression()
logistic.fit(x_train,y_train)
pred=logistic.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9236962395908616


array([[   938,    956],
       [ 15620, 199723]], dtype=int64)

### LDA

In [25]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA()
x_train,x_test,y_train,y_test = train_test_split(X,y)
x_train = lda.fit_transform(x_train, y_train)
x_test = lda.transform(x_test)
print(x_train,y_train)
print(x_train.shape,y_train.shape)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[-1.17947849]
 [-0.68019574]
 [ 1.44047963]
 ...
 [ 0.2142746 ]
 [ 0.13315535]
 [-0.81736191]] [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
(651709, 1) (651709, 1)


In [26]:
logistic=LogisticRegression()
logistic.fit(x_train,y_train)
pred=logistic.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9228906677960016


array([[  1694,   1655],
       [ 15096, 198792]], dtype=int64)