In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('C:/Users/sai kiran/Desktop/export_dataframe.csv')
data.head()

year  emp_length_int  home_ownership_cat  income_cat  loan_amount  \
0     4               2                   1           1            0   
1     4               0                   1           1            0   
2     4               2                   1           1            0   
3     4               2                   1           1            1   
4     4               0                   1           1            0   

   term_cat  purpose_cat  interest_payment_cat  loan_condition  interest_rate  \
0         1            1                     1               1              2   
1         2            2                     2               0              3   
2         1            3                     2               1              3   
3         1            4                     2               1              2   
4         2            4                     1               1              2   

   grade_cat  total_pymnt  total_rec_prncp  installment  region  
0          2            1                1            0       4  
1          3            0                0            0       0  
2          3            0                0            0       3  
3          3            2                2            1       1  
4          2            0                0            0       1

In [3]:
len(data)

868946

### PCA

In [4]:
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression,Perceptron
pca = PCA(n_components=11)
y=data['loan_condition'].values
data.drop('loan_condition',axis=1,inplace=True)
X=data[:].values
y=y.reshape(-1, 1)
x = pca.fit_transform(X)
x_train,x_test,y_train,y_test = train_test_split(x,y)
print(x,y)
print(x.shape,y.shape)

C:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


[[-3.89014161  0.70229024 -0.5539965  ... -0.18723329  0.11371368
   0.57003588]
 [-2.57951727 -0.47178081  1.07879067 ...  0.40621725  0.06890602
   0.40842075]
 [-1.63698094 -0.48746871  0.71798891 ... -0.41319872  0.12529852
   0.38122765]
 ...
 [ 1.36910677 -1.8013107   1.70012963 ...  0.3676323  -0.11947761
   0.04555552]
 [ 1.49016829 -1.78105474  2.44270258 ...  0.30771987 -0.08427237
   0.00783908]
 [-3.97930216  0.30563148  0.05818335 ... -0.6425049  -0.25165819
  -0.2203371 ]] [[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [1]]
(868946, 11) (868946, 1)


In [5]:
logistic=LogisticRegression()
logistic.fit(x_train,y_train)
pred=logistic.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9243545068289472


array([[  1450,   1364],
       [ 15069, 199354]], dtype=int64)

### SVD

In [6]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=7, n_iter=7, random_state=42)
x=svd.fit_transform(X)
x_train,x_test,y_train,y_test = train_test_split(x,y)
print(x,y)
print(x.shape,y.shape)

[[ 5.86311649 -1.94146222  0.9559941  ...  2.97837388  0.25000549
  -0.90587634]
 [ 6.0197011  -0.91226898 -0.48355861 ... -0.47292508  0.14684092
  -0.57750172]
 [ 7.1005899  -0.48488628 -0.53969513 ...  2.31815105  0.57393121
  -0.49440892]
 ...
 [11.30140821  0.20611554 -1.80283877 ... -1.47801614 -0.83923322
   0.19525852]
 [11.79770931 -0.04256594 -1.66522174 ...  0.56048299 -1.18360123
   0.41963723]
 [ 8.34040461 -3.51717606  1.10033237 ... -2.06798375 -1.06412554
  -0.08472932]] [[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [1]]
(868946, 7) (868946, 1)


In [7]:
logistic=LogisticRegression()
logistic.fit(x_train,y_train)
pred=logistic.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.923199086711748


array([[  1252,   1304],
       [ 15380, 199301]], dtype=int64)

### NMF

In [8]:
from sklearn.decomposition import NMF
clf = NMF(n_components=4)
x=clf.fit_transform(X)
x_train,x_test,y_train,y_test = train_test_split(x,y)
print(x,y)
print(x.shape,y.shape)

[[0.05196573 0.00534667 0.02757231 0.03490312]
 [0.0330109  0.01912181 0.         0.07290385]
 [0.04251581 0.02975414 0.00317833 0.06443892]
 ...
 [0.07008864 0.06199191 0.         0.07747214]
 [0.0721697  0.06096716 0.         0.08863169]
 [0.08589836 0.00205383 0.03694153 0.03307064]] [[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [1]]
(868946, 4) (868946, 1)


In [9]:
logistic=LogisticRegression()
logistic.fit(x_train,y_train)
pred=logistic.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.923774495136648


array([[   269,    327],
       [ 16232, 200409]], dtype=int64)

### LDA

In [10]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA()
x_train,x_test,y_train,y_test = train_test_split(X,y)
x_train = lda.fit_transform(x_train, y_train)
x_test = lda.transform(x_test)
print(x_train,y_train)
print(x_train.shape,y_train.shape)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[ 0.96349979]
 [-0.91595241]
 [ 0.19953202]
 ...
 [-1.38608964]
 [-1.16076172]
 [ 0.75388065]] [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
(651709, 1) (651709, 1)


In [11]:
logistic=LogisticRegression()
logistic.fit(x_train,y_train)
pred=logistic.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9233924239425144


array([[  1686,   1635],
       [ 15007, 198909]], dtype=int64)